sdk/src/main/java/cloud/mindbox/mobile_sdk/Configuration.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/IdentifierManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/InitData.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Requests.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/ValidationError.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/network/ServiceGenerator.kt

Изменения по результатам ревью кода / гарантированная доставка
ticket: https://trello.com/c/vpZ1dEXy

68 changes after review

---

app/src/main/java/com/mindbox/androidsdk/PushokMessagingService.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/DbManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/IdentifierManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MindboxEventManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Requests.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/ValidationError.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/network/MindboxServiceGenerator.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxBackgroundWorkManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxOneTimeEventWorker.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxPeriodicEventWorker.kt

Изменения по результатам ревью кода / гарантированная доставка
https://trello.com/c/vpZ1dEXy

Add runCatching

---

app/build.gradle
app/src/main/java/com/mindbox/androidsdk/MainActivity.kt
app/src/main/java/com/mindbox/androidsdk/screens/EnteringDataFragment.kt
gradle.properties
sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxBackgroundWorkManager.kt

Дополнительные ограничения воркера для режима энергосбережения - Гарантируемая доставка событий
https://trello.com/c/GeQueEaD

88 add worker battery limits

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MindboxEventManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Event.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/InitData.kt

Отслеживание клика
https://trello.com/c/YollxH1L

123 track clicks

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt

Проблема с большим объемом кэша
https://trello.com/c/KtmWjR7Z

118 cache issue

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt

Изменение алгоритма для получения deviceUUID из SDK
https://trello.com/c/MoOA9jVi

127 change deviceuuid method

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt

Проблема запуска воркера на андроид 4.4
https://trello.com/c/6ubdFg4p

116 android 4 worker

---

sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/Tools.kt
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/VersioningUnitTest.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/InitData.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt

[Ticket](https://trello.com/c/byjLWshI/134-android-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-applicationinfoupdated-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-applicationinfoupdated)
ToDo:
1. Added version field to InfoUpdated and ApplicationInstalled
2. Implemented versions counter in SharedPreferences with synchronising access
3. Implemented sending version in InfoUpdated and ApplicationInstalled

134 | Implementation of sending version with InfoUpdated and ApplicationInstalled events

---

.github/workflows/build.yml
.github/workflows/publish.yml
gradle.properties
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/LifecycleManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MindboxEventManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Event.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/InitData.kt

[Ticket](https://trello.com/c/ANyf69nL/159-android-%D1%82%D1%80%D0%B5%D0%BA%D0%B2%D0%B8%D0%B7%D0%B8%D1%82-%D1%82%D1%80%D0%B5%D0%BA%D0%B2%D0%B8%D0%B7%D0%B8%D1%82)
ToDo:
1. Implemented TrackVisit event
2. Implemented logic for handle app resume state

159 | Implemented handle for app become active

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Requests.kt

[Ticket](https://trello.com/c/xxBTfvna/167-android-%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%BB%D0%BE%D0%B3%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%BB%D0%BE%D0%B3%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)
ToDo:
1. Implemented checking BuildConfig.DEBUG before print logs about requests

167 | Implementation of checking debug version during creation log about requests

---

sdk/build.gradle
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/Tools.kt
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/VersioningUnitTest.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/MindboxConfiguration.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/SharedPreferencesManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt

[Ticket](https://trello.com/c/CNDlww2R/168-android-%D0%BE%D1%82%D0%BA%D0%B0%D0%B7-%D0%BE%D1%82-hawk-%D0%BE%D1%82%D0%BA%D0%B0%D0%B7-%D0%BE%D1%82-hawk)
ToDo:
1. Removed Hawk
2. Implemented using SharedPreferences for saving data
3. Implemented read and write data in SharedPreferences

168 | Changes from Hawk to SharedPreferences

---

gradle.properties

Release 1.0.31

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MindboxEventManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Event.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/OperationBody.kt

[Ticket](https://trello.com/c/UNiBYp18/173-android-v3-async)
1. Changes event structure
2. Implemented new public method
3. Implemented operation name checking
4. Implemented sending custom events

173 | Implementation of v3 async

---

gradle.properties
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MindboxEventManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Event.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/OperationBody.kt

Release 1.0.32

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/InitData.kt

[Ticket](https://trello.com/c/ylljYU10/188-android-%D0%BF%D0%B5%D1%80%D0%B5%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-lastdeviceuuid-%D0%B2-externaldeviceuuid-%D0%BF%D0%B5%D1%80%D0%B5%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-lastdeviceuuid-%D0%B2-externaldeviceuuid)
ToDo:
1. Changed lastDeviceUuid to externalDeviceUUID for Mobile.ApplicationInstalled event

188 Change of field lastDeviceUuid name for Mobile.ApplicationInstalled event

---

sdk/build.gradle
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/DeviceUuidRepeatedUnitTest.kt
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/DeviceUuidSingleUnitTest.kt
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/FmsTokenRepeatedUnitTest.kt
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/FmsTokenSingleUnitTest.kt
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/Tools.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/converters/MindboxRoomConverter.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/data/ConfigurationsDao.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/data/EventsDao.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/DbManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MindboxEventManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Configuration.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Event.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Requests.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxDatabase.kt

[Ticket](https://trello.com/c/tvUIrUhd/180-android-%D0%BF%D0%B5%D1%80%D0%B5%D0%B5%D0%B7%D0%B4-%D1%81-paperdb-%D0%BD%D0%B0-room-%D0%BF%D0%B5%D1%80%D0%B5%D0%B5%D0%B7%D0%B4-%D1%81-paperdb-%D0%BD%D0%B0-room)
ToDo:
1. Implemented using Room DB
2. Removed PaperDb
3. Implemented entities for Room
4. Implemented read and write operation
5. Implemented new filtering logic
6. Implemented lastRetryTime field for event
7. Improved unit tests

180 | Implementation of room database

---

gradle.properties
sdk/build.gradle
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/DeviceUuidRepeatedUnitTest.kt
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/DeviceUuidSingleUnitTest.kt
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/FmsTokenRepeatedUnitTest.kt
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/FmsTokenSingleUnitTest.kt
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/Tools.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/converters/MindboxRoomConverter.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/data/ConfigurationsDao.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/data/EventsDao.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/DbManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MindboxEventManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Configuration.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Event.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/InitData.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Requests.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxDatabase.kt

1. Implementation of Room DB
2. Changed field name from lastDeviceUuid to externalDeviceUUID

Release 1.0.33

---

gradle.properties
sdk/consumer-rules.pro

Release 1.0.34

---

sdk/src/main/AndroidManifest.xml
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/PushNotificationManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/InitData.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/PushAction.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Requests.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxPushReceiver.kt

[Ticket](https://trello.com/c/CM21gOSa/178-android-%D0%BE%D1%82%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BF%D1%83%D1%88%D0%B0-%D0%BE%D1%82%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BF%D1%83%D1%88%D0%B0)
ToDo:
1. Implemented public method for auto handle push
2. Implemented checking that push is from Mindbox
3. Implemented receiver for auto sending click event
4. Implementation of showing from 0 to 3 buttons in push

178 Implementation of push message autohandler

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Requests.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/request/LineRequest.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/AmountTypeResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/BalanceResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/BenefitResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/CustomerResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/DiscountCardResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/LimitResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/LimitTypeResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/NearestExpirationResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/OperationResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/PeriodType.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/PersonalOfferItemResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/ProcessingStatusResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/ProductResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/PromoActionResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/RetailOrderStatisticsResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/StatusResponse.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/TypeResponse.kt

- Implement GetAllCustomerFields operation
- Change `lineId` type in `LineRequest`
- Add  `name` field to `AreaResponse`
[Issue](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/128)

128 | Implement GetAllCustomerFieldsOperation

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/adapters/IdsAdapter.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/PointOfContactResponse.kt

- Fix bug with floating point Ids (no longer parsed as floating point number)
- Fix bug when parsing enums - support different letter cases of value

128 | v3 sync bugs

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/ProductListItemResponse.kt

128 | Add price field to ProductListItemResponse

---

sdk/src/main/AndroidManifest.xml
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/IdentifierManager.kt

[Issue](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/182)

18 | Generate random uuid if nulls were fetched from advertisement client

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MindboxEventManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/MindboxError.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/MindboxErrorAdapter.kt

[Issue](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/173)

17 | Sync/async operations json body

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/IdentifierManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt

[Issue](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/185)

19 | Enhance logging

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/MindboxConfiguration.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/SdkValidation.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/InputParametersUnitTest.kt

[Issue](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/186)

252 | Crit and non-crit validation errors

---

gradle.properties

Поддержка Huawei messaging service

Release 2.0.0

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt

[Issue](https://github.com/mindbox-moscow/issues-mobile-sdk/projects/1#:~:text=%D0%94%D0%BB%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9%20%D1%82%D0%B5%D0%BA%D1%81%D1%82%20%D0%BD%D0%B5%20%D0%BE%D1%82%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D1%8B%D0%B2%D0%B0%D0%B5%D1%82%D1%81%D1%8F%20%D0%BD%D0%B0%20%D0%BF%D1%83%D1%88%D0%B0%D1%85%20%23221)

221 | Display big text on notification

---

gradle.properties

[Добавили поддержку длинного текста при отрисовке пушей](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/221)

Release 2.0.1

---

sdk/consumer-rules.pro
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/MindboxWorkerFactory.kt

[Issue](https://github.com/mindbox-moscow/issues-mobile-sdk/projects/1#:~:text=%D0%A4%D0%B0%D0%B1%D1%80%D0%B8%D0%BA%D0%B0%20%D0%B4%D0%BB%D1%8F%20Worker%20%23228)

228 | WorkerFactory

---

gradle.properties

- [Изменен механизм гарантированной доставки](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/210): теперь ивенты совершают попытку отправиться сразу же, и в случае неудачи запускается механизм гарантированной доставки
- [Поддержка payload в пушах](https://github.com/mindbox-moscow/issues-mobile-sdk/projects/1#:~:text=%D0%9F%D1%80%D0%BE%D0%BA%D0%B8%D0%B4%D1%8B%D0%B2%D0%B0%D1%82%D1%8C%20payload%20%D0%B8%D0%B7%20%D0%BF%D1%83%D1%88%D0%B0%20%D0%BF%D1%80%D0%B8%20%D0%BE%D1%82%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%BA%D0%B5%20%D0%BD%D0%B0%D1%88%D0%B8%D0%BC%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%BC%20%23227)
- [Добавлена поддержка кастомной инициализации WorkManager](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/228)

Release 2.1.0

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt

[Issue](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/245)

245 |  Init push service method

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushAction.kt

[Issue](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/254)

254 | Push buttons aren't showing on release build

---

git-release.sh
gradle.properties

[Bug: Push buttons not showing on release build #254](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/254)
Fixed bug

Set version to 2.1.2

---

mindbox-firebase/src/main/java/cloud/mindbox/mindbox_firebase/FirebaseServiceHandler.kt
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/ConfigurationUpdateUnitTest.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/data/ConfigurationsDao.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/data/EventsDao.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/DbManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/ConfigUpdate.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/network/MindboxServiceGenerator.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt

[Issue](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/246)

246 | SDK reinitialization

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt

[Issue](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/260)

260 | Show text on push preview

---

gradle.properties

[Send InfoUpdated when application is moved in foreground #257](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/257)
Mindbox SDK will now check for updates in Messaging Services (i.e. for new push token or services availability in general) and will send InfoUpdated events whenever application is moved to foreground.
---
[Push body preview on notifications #260](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/260)
Fixed bug when push body wasn’t visible on collapsed notification

Release 2.1.4

---

dependencies.gradle

Task: https://github.com/mindbox-moscow/issues-mobile-sdk/issues/268

268 | Update hms_push version

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxBackgroundWorkManager.kt

Issue: https://github.com/mindbox-moscow/issues-mobile-sdk/issues/270

270 | Replaced cancelling all work with canceling by tag

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/LifecycleManager.kt

275 | Crash fix in LifecycleManager event

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt

https://github.com/mindbox-moscow/issues-mobile-sdk/issues/276
https://trello.com/c/dogUwJ7E

276 Subscription methods improvement

---

.gitignore
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/MindboxConfiguration.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/LifecycleManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/UuidCopyManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Configuration.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt

https://github.com/mindbox-moscow/issues-dev2/issues/1881

1881_debug_device_uuid_added

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/InitData.kt

https://github.com/mindbox-moscow/issues-dev2/issues/1880

1880 add timezone to application installed

---

sdk/build.gradle
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/DeviceUuidSingleUnitTest.kt
sdk/src/androidTest/java/cloud/mindbox/mobile_sdk/FmsTokenSingleUnitTest.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/SharedPreferencesManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt

https://github.com/mindbox-moscow/issues-dev2/issues/1927

1927_fix_device_uuid_generate_race_condition

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MindboxEventManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt

https://github.com/mindbox-moscow/issues-dev2/issues/1925

1925 fix negative offsets

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt

https://github.com/mindbox-moscow/issues-mailings/issues/68

68-fix-notifications-enabled-flag

---

.gitignore
gradle.properties
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/MindboxConfiguration.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/LifecycleManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/UuidCopyManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Configuration.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt

Release 2.1.7

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/handler/image/MindboxImageLoaderDefault.kt

https://github.com/mindbox-moscow/issues-devM/issues/2055

2055-bug_no_image_in_rich_push

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/InAppRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractor.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppRepository.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/mapper/InAppMessageMapper.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageManager.kt

https://github.com/mindbox-moscow/issues-devM/issues/2056

2056 fix error on inapp config 404

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt

Fixes https://github.com/mindbox-moscow/android-sdk/issues/271

Fix startKoin conflicting with a koin instance of the app

---

dependencies.gradle
mindbox-firebase/build.gradle
mindbox-huawei/build.gradle
modulesCommon.gradle
sdk/build.gradle
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/di/MindboxKoin.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/di/Modules.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/logger/MindboxLoggerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/MonitoringDao.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/MonitoringDatabase.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/MonitoringEntity.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/MonitoringManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/MonitoringMapper.kt

https://github.com/mindbox-moscow/issues-web-mobile/issues/2085

adding log saving

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/MindboxConfiguration.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/LifecycleManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MindboxEventManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Requests.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/network/MindboxServiceGenerator.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushServiceHandler.kt

https://github.com/mindbox-moscow/issues-web-mobile/issues/2087

2087 add logs

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/di/Modules.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/InAppRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/data/repositories/MonitoringRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/data/rmappers/MonitoringMapper.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/data/validators/MonitoringValidator.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/ExtensionsTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/monitoring/MonitoringRepositoryImplTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/monitoring/MonitoringValidatorTest.kt

[[Android] У клиента Токио-сити логируются только записи с уровнем Fatal и Error#2331](https://github.com/mindbox-cloud/issues-web-mobile/issues/2331)

Mbx 2331 log fixes

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/di/Modules.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppChoosingManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/models/InAppConfig.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/models/TreeTargeting.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppChoosingManagerTest.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/2437

fixing logic of segment and geo

---

sdk/build.gradle
sdk/src/main/java/cloud/mindbox/mobile_sdk/di/Modules.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/InAppRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppChoosingManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppPicassoImageLoaderImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/repositories/InAppRepository.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/res/values/strings.xml
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppChoosingManagerTest.kt

[[Android] Ошибка загрузки картинки приводит к скипу всех инапов#2456](https://github.com/mindbox-cloud/issues-web-mobile/issues/2456)

fixing picasso

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt

https://github.com/orgs/mindbox-cloud/projects/69/views/1?pane=issue&itemId=25306640

adding delayed request config

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/InitializeLock.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/DbManager.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/2642

MBX-2642: Fix soft reinit lock

---

modulesCommon.gradle
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/2640

Fix jitpack build signing

---

sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/validators/OperationNameValidatorTest.kt

test MBX-2475

---

dependencies.gradle
mindbox-firebase/build.gradle
mindbox-huawei/build.gradle
modulesCommon.gradle
sdk/build.gradle
sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/MobileConfigRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/logger/MindboxLoggerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/data/repositories/MonitoringRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/data/validators/MonitoringValidator.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/domain/interfaces/LogResponseDataManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/domain/interfaces/MonitoringRepository.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/domain/managers/LogResponseDataManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/domain/models/LogRequest.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/domain/models/LogResponse.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/ExtensionsTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/monitoring/LogRequestStub.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/monitoring/LogResponseStub.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/monitoring/domain/managers/LogRequestDataManagerImplTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/monitoring/domain/managers/LogResponseDataManagerImplTest.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/2685

replacing java time with android three ten

---

.idea/codeStyles/Project.xml
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MindboxEventManager.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/2753

MBX-2753: Fix handle event before generate device uuid

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/logger/MindboxLoggerImpl.kt

[[Android] Установить дефолтный уровень логирования Warning#2749](https://github.com/mindbox-cloud/issues-web-mobile/issues/2749)

MBX-2749: Change default log level to WARN

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/InAppGlideImageLoaderImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/ModalWindowInAppViewHolder.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/SnackbarInAppViewHolder.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/2813

fix image loading

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageViewDisplayerImpl.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/2813

fix inapp click

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/SnackbarInAppViewHolder.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/2837

fixing layer size

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/InAppGlideImageLoaderImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/2871

handle exception in glide

---

mindbox-firebase/src/main/java/cloud/mindbox/mindbox_firebase/FirebaseServiceHandler.kt
mindbox-firebase/src/main/java/cloud/mindbox/mindbox_firebase/MindboxFirebase.kt
mindbox-huawei/src/main/java/cloud/mindbox/mindbox_huawei/HuaweiServiceHandler.kt
mindbox-huawei/src/main/java/cloud/mindbox/mindbox_huawei/MindboxHuawei.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MindboxPushService.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/2901

MBX-2901: Add updatePushToken fix

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/validators/JsonValidator.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/validators/JsonValidatorTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/validators/XmlValidatorTest.kt

[#3043](https://github.com/mindbox-cloud/issues-web-mobile/issues/3043)

Changed JsonValidator

---

mindbox-firebase/src/test/kotlin/cloud/mindbox/mindbox_firebase/MindboxFirebaseTest.kt
mindbox-huawei/src/main/java/cloud/mindbox/mindbox_huawei/HuaweiMessage.kt
mindbox-huawei/src/main/java/cloud/mindbox/mindbox_huawei/MindboxHuawei.kt
mindbox-huawei/src/test/kotlin/cloud/mindbox/mindbox_huawei/MindboxHuaweiTest.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/3155

MBX-3155: fix null title for Huawei

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/DataModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/dto/BackgroundDto.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/mapper/InAppMapper.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/validators/ImageLayerValidator.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/models/Layer.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/Constants.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/TypeAliases.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/validators/ImageLayerValidatorTest.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/3182

MBX-3182: supported action type "pushPermission"

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/DomainModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/MindboxModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/UserVisitManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/UserVisitManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/managers/UserVisitManagerTest.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/3209

MBX-3209: adding user visit count

---

dependencies.gradle

https://github.com/mindbox-cloud/issues-web-mobile/issues/3297

MBX-3297: up version for gson and kotlin-stdlib

---

sdk/consumer-rules.pro

https://github.com/mindbox-cloud/issues-web-mobile/issues/3321

MBX-3321: added inapp dto for proguard

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/Constants.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/utils/MigrationManagerTest.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/3389

[Android] Добавить возможность использовать изменение версии SDK

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/mapper/InAppMapper.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/MobileConfigRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/validators/InAppConfigTtlValidator.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/validators/TtlParametersValidator.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/InAppConfigResponse.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/ParseTimeSpanTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/validators/InAppConfigTtlValidatorTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/validators/TtlParametersValidatorTest.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/3418

MBX-3418: Change ttl format to TimeSpan

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/InAppConfigResponse.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/3414

MBX-3414: fixing time units

---

dependencies.gradle
example/app/src/main/AndroidManifest.xml

https://github.com/mindbox-cloud/issues-web-mobile/issues/3374

MBX-3374: Update hms.push version

---

example/app/build.gradle
example/app/src/main/AndroidManifest.xml
example/app/src/main/java/com/mindbox/example/ActivityTransitionByPush.kt
example/app/src/main/java/com/mindbox/example/MainActivity.kt
example/app/src/main/java/com/mindbox/example/MindboxFirebaseMessagingService.kt
example/app/src/main/java/com/mindbox/example/MindboxHuaweiMessagingService.kt
example/app/src/main/java/com/mindbox/example/NotificationAdapter.kt
example/app/src/main/java/com/mindbox/example/NotificationHistoryActivity.kt
example/app/src/main/java/com/mindbox/example/NotificationStorage.kt
example/app/src/main/java/com/mindbox/example/PushPayload.kt
example/app/src/main/res/layout/activity_main.xml
example/app/src/main/res/layout/activity_notification_history_activivity.xml
example/app/src/main/res/layout/item_notification.xml
example/app/src/main/res/values/strings.xml

https://github.com/mindbox-cloud/issues-web-mobile/issues/3428

Feature/MBX-3388: Adding Notification Center

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/ImagePushSizeManager.kt
sdk/src/main/res/values/bools.xml

https://github.com/mindbox-cloud/issues-web-mobile/issues/3508

MBX-3508: notification center inside image

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/3547

MBX-3547: add logging public method

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/ImagePushSizeManager.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/3508

MBX-3508: fix size

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MindboxEventManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Event.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/3565

MBX-3565: remove push delivery event

---

modulesCommon.gradle

https://github.com/mindbox-cloud/issues-web-mobile/issues/3567

MBX-3567: Change publishing information

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/DataModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/MindboxModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/utils/MigrationManagerTest.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/3618

MBX-3612: fix many executions of migration

---

.github/workflows/deploy.yml

[[Mobile] Привести версии пушков к версии SDK](https://github.com/mindbox-cloud/issues-web-mobile/issues/3617)

MBX-3617 Build workflow

---

example/app/src/main/java/com/mindbox/example/MindboxHuaweiMessagingService.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/3675

MBX-3675: handle remoteMessage asynchronously for HMS

---

build.gradle
example/app/build.gradle
example/build.gradle
example/gradle/wrapper/gradle-wrapper.properties
gradle.properties
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
mindbox-firebase/build.gradle
mindbox-firebase/src/main/AndroidManifest.xml
mindbox-huawei/build.gradle
mindbox-huawei/src/main/AndroidManifest.xml
modulesCommon.gradle
sdk/build.gradle
sdk/src/main/AndroidManifest.xml
sdk/src/main/java/cloud/mindbox/mobile_sdk/monitoring/data/room/MonitoringDatabase.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxDatabase.kt
settings.gradle

https://github.com/mindbox-cloud/issues-web-mobile/issues/3117

MBX-3117: Upgrade gradle to 8.7

---

mindbox-firebase/build.gradle
mindbox-huawei/build.gradle
sdk/build.gradle

https://github.com/mindbox-cloud/issues-web-mobile/issues/3738

MBX-3736: Change path for proguard rules

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppProcessingManagerImpl.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppProcessingManagerTest.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/3647

MBX-3647: Fix crash fetchTargetingInfo

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/SharedPreferencesManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/InitData.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushServiceHandler.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushToken.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/Constants.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/LoggingExceptionHandler.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/MindboxTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/pushes/PushTokenTest.kt

https://tracker.yandex.ru/WMRUSTORE-5

WMRUSTORE-5: Add multi tokens

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/MindboxTest.kt

[WMRUSTORE-6: Поддержка нового формата токенов iOS](https://tracker.yandex.ru/WMRUSTORE-5)

WMRUSTORE-5: Fix empty tokens on firstInit

---

example/app/build.gradle
example/app/src/main/AndroidManifest.xml
example/app/src/main/java/com/mindbox/example/ExampleApplication.kt
example/app/src/main/java/com/mindbox/example/MindboxRuStoreMessagingService.kt
example/settings.gradle
mindbox-rustore/src/main/java/cloud/mindbox/mindbox_rustore/MindboxRuStore.kt

https://tracker.yandex.ru/WMRUSTORE-9

WMRUSTORE-9: Add rustore to example

---

mindbox-rustore/build.gradle.kts
mindbox-rustore/src/main/java/cloud/mindbox/mindbox_rustore/MindboxRuStore.kt
mindbox-rustore/src/main/java/cloud/mindbox/mindbox_rustore/RuStoreMessage.kt
mindbox-rustore/src/main/java/cloud/mindbox/mindbox_rustore/RuStoreServiceHandler.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt

https://tracker.yandex.ru/WMRUSTORE-7

WMRUSTORE-7: Add push Rustore push handler

---

mindbox-firebase/src/main/java/cloud/mindbox/mindbox_firebase/FirebaseServiceHandler.kt
mindbox-huawei/src/main/java/cloud/mindbox/mindbox_huawei/HuaweiServiceHandler.kt
mindbox-rustore/src/main/java/cloud/mindbox/mindbox_rustore/RuStoreServiceHandler.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/InitializeLock.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/logger/MindboxLoggerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushServiceHandler.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/Stopwatch.kt

https://tracker.yandex.ru/WMRUSTORE-12

WMRUSTORE-12: Fix migration tokens format

---

example/app/build.gradle
gradle/libs.versions.toml
mindbox-rustore/src/main/java/cloud/mindbox/mindbox_rustore/RuStoreServiceHandler.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt

https://tracker.yandex.ru/WMRUSTORE-12

WMRUSTORE-12: Fix rustore init crash

---

example/app/build.gradle
gradle/libs.versions.toml
mindbox-firebase/gradle.properties
mindbox-firebase/src/main/java/cloud/mindbox/mindbox_firebase/FirebaseServiceHandler.kt
mindbox-huawei/gradle.properties
mindbox-huawei/src/main/java/cloud/mindbox/mindbox_huawei/HuaweiServiceHandler.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/MindboxNotificationManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppConstraintLayout.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushServiceHandler.kt

https://tracker.yandex.ru/WMSDK-391

WMSDK-391: bump minSdk version

---

mindbox-rustore/src/main/java/cloud/mindbox/mindbox_rustore/MindboxRuStore.kt
mindbox-rustore/src/main/java/cloud/mindbox/mindbox_rustore/RuStoreServiceHandler.kt

[WMRUSTORE-24](https://tracker.yandex.ru/WMRUSTORE-24)

WMRUSTORE-10: Add RuStore meta-data init

---

mindbox-huawei/src/main/java/cloud/mindbox/mindbox_huawei/HuaweiMessage.kt
mindbox-huawei/src/main/java/cloud/mindbox/mindbox_huawei/HuaweiPushActionsDeserializer.kt
mindbox-huawei/src/main/java/cloud/mindbox/mindbox_huawei/MindboxHuawei.kt
mindbox-huawei/src/test/kotlin/cloud/mindbox/mindbox_huawei/MindboxHuaweiTest.kt

https://tracker.yandex.ru/WMSDK-396

WMSDK-396: add HuaweiPushActionsDeserializer

---

mindbox-huawei/consumer-rules.pro

https://tracker.yandex.ru/WMSDK-396

WMSDK-396: add proguard rules for huawei

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageViewDisplayerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushServiceHandler.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushToken.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/Stopwatch.kt

https://tracker.yandex.ru/WMRUSTORE-14

WMRUSTORE-14: Retrieve push tokens async

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/DataModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/MindboxModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/SessionStorageManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/TimeProvider.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/managers/SessionStorageManagerTest.kt

https://tracker.yandex.ru/WMSDK-400

WMSDK-400: added checking inapp session

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt

https://tracker.yandex.ru/WMRUSTORE-35

WMRUSTORE-35: Add timeout for init push services

---

example/app/build.gradle
example/app/src/main/AndroidManifest.xml
example/app/src/main/java/com/mindbox/example/ExampleApplication.kt
example/app/src/main/java/com/mindbox/example/MainActivity.kt

https://tracker.yandex.ru/WMRUSTORE-22

WMRUSTORE-22: Prepare example app for rustore release

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/SessionStorageManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/InAppRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/MobileConfigRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/interactors/InAppInteractor.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/repositories/InAppRepository.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/repositories/MobileConfigRepository.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageViewDisplayer.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageViewDisplayerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/ModalWindowInAppViewHolder.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MindboxEventManager.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageManagerTest.kt

https://tracker.yandex.ru/WMSDK-404

WMSDK-404: request config after reopen in-app session

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushToken.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/CoroutineExtensions.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/utils/CoroutineExtensionsKtTest.kt

https://tracker.yandex.ru/WMRUSTORE-35

WMRUSTORE-35: Fix timeouts for initPushServices and getPushTokens

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/DataModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/MindboxModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/MobileConfigSerializationManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/SessionStorageManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/mapper/InAppMapper.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/MobileConfigRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/validators/SlidingExpirationParametersValidator.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MobileConfigSettingsManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MobileConfigSettingsManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/InAppConfigResponse.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/managers/SessionStorageManagerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/validators/SlidingExpirationParametersValidator.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/validators/SlidingExpirationParametersValidatorTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/managers/MobileConfigSettingsManagerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/models/SettingsStub.kt
sdk/src/test/resources/ConfigParsing/Config/ConfigWithSettingsABTestsMonitoringInapps.json

https://tracker.yandex.ru/WMSDK-402

WMSDK-402: support slidingExpiration at config

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt

https://tracker.yandex.ru/WMSDK-409

WMSDK-409: removed  runBlocking in onTrackVisitReady

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/mapper/InAppMapper.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/MobileConfigRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/validators/SlidingExpirationParametersValidator.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/MobileConfigSettingsManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/InAppConfigResponse.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/managers/serialization/SettingsMobileConfigSerializationManagerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/models/SettingsStub.kt
sdk/src/test/resources/ConfigParsing/Config/ConfigWithSettingsABTestsMonitoringInapps.json
sdk/src/test/resources/ConfigParsing/ConfigWithSettingsABTestsMonitoringInapps.json
sdk/src/test/resources/ConfigParsing/Settings/SlidingExpirationErrors/SettingsSlidingExpirationConfigTypeError.json
sdk/src/test/resources/ConfigParsing/Settings/SlidingExpirationErrors/SettingsSlidingExpirationConfigsError.json
sdk/src/test/resources/ConfigParsing/Settings/SlidingExpirationErrors/SettingsSlidingExpirationError.json
sdk/src/test/resources/ConfigParsing/Settings/SlidingExpirationErrors/SettingsSlidingExpirationTypeError.json

https://tracker.yandex.ru/WMSDK-410

WMSDK-410: change slidingExpiration contract

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageManagerImpl.kt

https://tracker.yandex.ru/WMSDK-413

WMSDK-413: call hideCurrentInApp in main thread

---

.github/workflows/distribute-develop.yml
.github/workflows/distribute-release-support.yml
.github/workflows/distribute-reusable.yml

Собираем сборку если 
1. Вмержили ПР в девелоп
2. Открыли или добавили коммит в ПР, который нацелен на master ветку.

WMSDK-0000-Pushok-after-merge-and-sync

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt

https://tracker.yandex.ru/WMSDK-429

WMSDK-429: added await of SAVE_MINDBOX_CONFIG

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppProcessingManagerImpl.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppProcessingManagerTest.kt

https://tracker.yandex.ru/WMSDK-378

WMSDK-378: fix bug

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/ExtensionsTest.kt

https://tracker.yandex.ru/WMSDK-431

Added extensions method for put push unique key to intent

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/DomainModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/SessionStorageManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/InAppSegmentationRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/repositories/InAppSegmentationRepository.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/models/ViewProductSegmentNode.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/managers/SessionStorageManagerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/InAppSegmentationRepositoryTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppProcessingManagerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/domain/models/ViewProductSegmentNodeTest.kt

https://tracker.yandex.ru/WMSDK-427

WMSDK-427: request product segment for every product id

---

sdk/src/main/assets/inapp.html
sdk/src/main/assets/webview.html
sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/DataModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/dto/BackgroundDto.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/dto/FormBlankDto.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/dto/PayloadDto.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/InAppContentFetcherImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/MobileConfigSerializationManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/data_filler/DataManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/mapper/InAppMapper.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/MobileConfigRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/validators/ModalWindowValidator.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/validators/SnackbarValidator.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/models/InAppConfig.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/models/Layer.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageViewDisplayerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppConstraintLayout.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/ModalWindowInAppViewHolder.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/SnackbarInAppViewHolder.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/WebAppInterface.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/WebViewInAppViewHolder.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Configuration.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Requests.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/Constants.kt
sdk/src/main/res/layout/mindbox_inapp_layout.xml

WebView Inapp prototype
https://tracker.yandex.ru/WMSDK-439

WMSDK-439: Add webview inapp

---

.github/workflows/distribute-develop.yml
.github/workflows/distribute-manual.yml
.github/workflows/distribute-release-support.yml
.github/workflows/distribute-reusable.yml
.github/workflows/publish-from-master-or-support.yml
.github/workflows/publish-manual.yml
.github/workflows/publish-rc-mission.yml
.github/workflows/publish-reusable.yml
.github/workflows/release-version-check.yml

https://tracker.yandex.ru/WMSDK-441

WMSDK-441: change publish flow

---

.github/workflows/manual-prepare_release_branch.yml

https://tracker.yandex.ru/WMSDK-441

fix file name

---

.github/workflows/publish-reusable.yml

AutoMerge for PR from master to dev

WMSDK-450: Create auto mergable pr from master to dev

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/DataModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/MindboxModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/dto/deserializers/InappSettingsDtoBlankDeserializer.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/dto/deserializers/JsonElementExtensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/MobileConfigSerializationManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/MobileConfigRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/validators/IntegerPositiveValidator.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/validators/TimeSpanPositiveValidator.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/InappSettingsManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/InappSettingsManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Milliseconds.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/TimeSpan.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/InAppConfigResponse.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/dto/deserializers/InappSettingsDtoBlankDeserializerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/dto/deserializers/JsonElementExtensionsTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/managers/serialization/SettingsMobileConfigSerializationManagerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/validators/IntegerPositiveValidatorTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/validators/TimeSpanPositiveValidatorTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/managers/MobileConfigSettingsManagerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/models/SettingsStub.kt
sdk/src/test/resources/ConfigParsing/Settings/InappSettingsErrors/InappSettingsConfigTypeError.json
sdk/src/test/resources/ConfigParsing/Settings/InappSettingsErrors/InappSettingsConfigsError.json
sdk/src/test/resources/ConfigParsing/Settings/InappSettingsErrors/InappSettingsError.json
sdk/src/test/resources/ConfigParsing/Settings/InappSettingsErrors/InappSettingsTypeError.json

https://tracker.yandex.ru/WMSDK-463

WMSDK-463: support inapp block in mobile config

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/SessionStorageManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/mapper/InAppMapper.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/InAppRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppFrequencyManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/interactors/InAppInteractor.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/repositories/InAppRepository.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/models/InAppConfig.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageViewDisplayerImpl.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/managers/SessionStorageManagerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/InAppRepositoryTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppFrequencyManagerImplTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageManagerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/models/InAppStub.kt

https://tracker.yandex.ru/WMSDK-467

WMSDK-467: Removed limit on number of inapps shown per session

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/SessionStorageManager.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/managers/SessionStorageManagerTest.kt

https://tracker.yandex.ru/WMSDK-446

WMSDK-446: Add AtomicLong for lastTrackVisitSendTime

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/DataModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/checkers/MaxInappsPerDayLimitChecker.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/managers/InAppSerializationManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/InAppRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppFrequencyManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/managers/InAppSerializationManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/repositories/InAppRepository.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Timestamp.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/CalendarUtils.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/Constants.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/MigrationManager.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/checkers/MaxInappsPerDayLimitCheckerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/managers/InAppSerializationManagerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/InAppRepositoryTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppFrequencyManagerImplTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/utils/CalendarUtilsTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/utils/MigrationManagerTest.kt

https://tracker.yandex.ru/WMSDK-470

WMSDK-470: added day limit checker for in-app messages

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/DataModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/di/modules/DomainModule.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/checkers/MaxInappsPerDayLimitChecker.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/checkers/MinIntervalBetweenShowsLimitChecker.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/InAppRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/InAppActionCallbacks.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/InAppLifecycleCallbacks.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/interactors/InAppInteractor.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/repositories/InAppRepository.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/models/InAppTypeWrapper.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageViewDisplayer.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageViewDisplayerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Timestamp.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/TimeProvider.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/checkers/MaxInappsPerDayLimitCheckerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/checkers/MinIntervalBetweenShowsLimitCheckerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageManagerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/managers/MobileConfigSettingsManagerTest.kt

https://tracker.yandex.ru/WMSDK-475

WMSDK-475: support min interval between inapp show duration

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/dto/deserializers/InAppIsPriorityDeserializer.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/dto/deserializers/JsonElementExtensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/mapper/InAppMapper.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppProcessingManagerImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/interfaces/managers/InAppProcessingManager.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/models/InAppConfig.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/InAppConfigResponse.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/dto/deserializers/InAppIsPriorityDeserializerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/mapper/InAppMapperTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppProcessingManagerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/models/InAppStub.kt
sdk/src/test/resources/ConfigParsing/Config/ConfigInAppsError.json
sdk/src/test/resources/ConfigParsing/Config/ConfigWithSettingsABTestsMonitoringInapps.json
sdk/src/test/resources/ConfigParsing/ConfigWithSettingsABTestsMonitoringInapps.json

https://tracker.yandex.ru/WMSDK-478

WMSDK-478: Add isPriority field support with false default

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt

https://tracker.yandex.ru/WMSDK-482

WMSDK-482: Fix inAppMutex DCL

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/InAppRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImplTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/presentation/InAppMessageManagerTest.kt

https://tracker.yandex.ru/WMSDK-481

WMSDK-481: added logic for priority inapp

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/ExtensionsTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/managers/GatewayManagerTest.kt

https://tracker.yandex.ru/WMSDK-480

WMSDK-480: Add deviceUUID to segments requests

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/dto/deserializers/InAppDelayTimeDeserializer.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/dto/deserializers/InAppIsPriorityDeserializer.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/dto/deserializers/JsonElementExtensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/mapper/InAppMapper.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/MobileConfigRepositoryImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/InAppInteractorImpl.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/domain/models/InAppConfig.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/Milliseconds.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/TimeSpan.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/models/operation/response/InAppConfigResponse.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/dto/deserializers/InAppDelayTimeDeserializerTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/mapper/InAppMapperTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/inapp/data/repositories/MobileConfigRepositoryImplTest.kt
sdk/src/test/java/cloud/mindbox/mobile_sdk/models/InAppStub.kt
sdk/src/test/resources/ConfigParsing/Config/ConfigInAppsError.json
sdk/src/test/resources/ConfigParsing/Config/ConfigWithSettingsABTestsMonitoringInapps.json
sdk/src/test/resources/ConfigParsing/ConfigWithSettingsABTestsMonitoringInapps.json

https://tracker.yandex.ru/WMSDK-486

WMSDK-486: delayTime parsing

---

.github/workflows/publish-reusable.yml
example/app/build.gradle
gradle.properties
gradle/libs.versions.toml
modulesCommon.gradle

Updates the release version to 2.13.5-rc. Automated PR: merge release/2.13.5-rc into mission/in-app-survey

Release 2.13.5-rc

---

.github/workflows/publish-reusable.yml
example/app/build.gradle
gradle.properties
gradle/libs.versions.toml
modulesCommon.gradle

Updates the release version to 2.14.0-rc. Automated PR: merge release/2.14.0-rc into mission/inapp-display-control

Release 2.14.0-rc

---

gradle/libs.versions.toml
sdk/build.gradle
sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppConstraintLayout.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppImageView.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppPositionController.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
sdk/src/main/res/values/bools.xml

https://tracker.yandex.ru/WMSDK-498

WMSDK-498: support inapp show on fragments

---

example/app/build.gradle

bump targetSdk version

---

.github/workflows/publish-reusable.yml
example/app/build.gradle
gradle.properties
gradle/libs.versions.toml
modulesCommon.gradle
sdk/build.gradle
sdk/src/main/java/cloud/mindbox/mobile_sdk/Extensions.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppConstraintLayout.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppImageView.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppPositionController.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
sdk/src/main/res/values/bools.xml

Updates the release version to 2.13.5. Automated PR: merge release/2.13.5 into develop

Release 2.13.5

---

.github/workflows/publish-reusable.yml

WMSDK-0000: change check to lint

---

sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/AbstractInAppViewHolder.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppImageView.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/InAppPositionController.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/ModalWindowInAppViewHolder.kt
sdk/src/main/java/cloud/mindbox/mobile_sdk/inapp/presentation/view/SnackbarInAppViewHolder.kt
sdk/src/main/res/layout/mindbox_blur_layout.xml
sdk/src/main/res/layout/mindbox_inapp_layout.xml
sdk/src/main/res/values/colors.xml

https://tracker.yandex.ru/WMSDK-513

WMSDK-513: Add container for inapp layout

---

gradle/libs.versions.toml

https://tracker.yandex.ru/WMSDK-545

WMSDK-545: update submodule

---

gradle.properties
gradle/libs.versions.toml
sdk/build.gradle

https://tracker.yandex.ru/WMSDK-545

WMSDK-545: remove mindbox_common version

---

gradle/libs.versions.toml
sdk/build.gradle

https://tracker.yandex.ru/WMSDK-545

WMSDK-545: remove mindbox-common constraints
